{{ $fullname := include "fullname"  . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    role: cronjob
data:
  project: {{ .Values.project | b64enc }}
  event : {{ default "cron" .Values.event | b64enc }}
  ref: {{ default "master" .Values.ref | b64enc }}
  {{ if .Values.commit}}
  commit: {{ .Values.commit | b64enc }}
  {{ end }}
  {{ if .Values.payload }}
  "payload.dat": {{ .Values.payload | b64enc }}
  {{ end }}
  {{ if .Values.script }}
  "brigade.js": {{ .Values.script| b64enc }}
  {{ end }}
